services:
  postgres:
    image: postgres:15
    container_name: restsim_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: restsim
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data